In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [8]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [11]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [14]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [16]:
ann.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [17]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 539us/step - loss: 0.6163 - accuracy: 0.6919
Epoch 2/100
250/250 [==============================] - 0s 499us/step - loss: 0.4885 - accuracy: 0.7987
Epoch 3/100
250/250 [==============================] - 0s 499us/step - loss: 0.4506 - accuracy: 0.8048
Epoch 4/100
250/250 [==============================] - 0s 502us/step - loss: 0.4278 - accuracy: 0.8115
Epoch 5/100
250/250 [==============================] - 0s 497us/step - loss: 0.4134 - accuracy: 0.8179
Epoch 6/100
250/250 [==============================] - 0s 502us/step - loss: 0.4013 - accuracy: 0.8249
Epoch 7/100
250/250 [==============================] - 0s 504us/step - loss: 0.3902 - accuracy: 0.8324
Epoch 8/100
250/250 [==============================] - 0s 516us/step - loss: 0.3791 - accuracy: 0.8374
Epoch 9/100
250/250 [==============================] - 0s 504us/step - loss: 0.3700 - accuracy: 0.8441
Epoch 10/100
250/250 [==============================] - 0s 501us/step - l

250/250 [==============================] - 0s 500us/step - loss: 0.3369 - accuracy: 0.8626
Epoch 80/100
250/250 [==============================] - 0s 506us/step - loss: 0.3362 - accuracy: 0.8637
Epoch 81/100
250/250 [==============================] - 0s 491us/step - loss: 0.3364 - accuracy: 0.8655
Epoch 82/100
250/250 [==============================] - 0s 491us/step - loss: 0.3362 - accuracy: 0.8649
Epoch 83/100
250/250 [==============================] - 0s 588us/step - loss: 0.3361 - accuracy: 0.8637
Epoch 84/100
250/250 [==============================] - 0s 512us/step - loss: 0.3361 - accuracy: 0.8644
Epoch 85/100
250/250 [==============================] - 0s 499us/step - loss: 0.3363 - accuracy: 0.8629
Epoch 86/100
250/250 [==============================] - 0s 494us/step - loss: 0.3353 - accuracy: 0.8636
Epoch 87/100
250/250 [==============================] - 0s 495us/step - loss: 0.3361 - accuracy: 0.8646
Epoch 88/100
250/250 [==============================] - 0s 491us/step - loss:

In [18]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 465us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [19]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 190  215]]


0.861